/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as KegiatanRouteImport } from './routes/kegiatan'
import { Route as DonasiRouteImport } from './routes/donasi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LaporanIndexRouteImport } from './routes/laporan/index'
import { Route as LaporanSlugRouteImport } from './routes/laporan/$slug'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const KegiatanRoute = KegiatanRouteImport.update({
  id: '/kegiatan',
  path: '/kegiatan',
  getParentRoute: () => rootRouteImport,
} as any)
const DonasiRoute = DonasiRouteImport.update({
  id: '/donasi',
  path: '/donasi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanIndexRoute = LaporanIndexRouteImport.update({
  id: '/laporan/',
  path: '/laporan/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanSlugRoute = LaporanSlugRouteImport.update({
  id: '/laporan/$slug',
  path: '/laporan/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/donasi': typeof DonasiRoute
  '/kegiatan': typeof KegiatanRoute
  '/tentang': typeof TentangRoute
  '/laporan/$slug': typeof LaporanSlugRoute
  '/laporan/': typeof LaporanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/donasi': typeof DonasiRoute
  '/kegiatan': typeof KegiatanRoute
  '/tentang': typeof TentangRoute
  '/laporan/$slug': typeof LaporanSlugRoute
  '/laporan': typeof LaporanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/donasi': typeof DonasiRoute
  '/kegiatan': typeof KegiatanRoute
  '/tentang': typeof TentangRoute
  '/laporan/$slug': typeof LaporanSlugRoute
  '/laporan/': typeof LaporanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/donasi' | '/kegiatan' | '/tentang' | '/laporan/$slug' | '/laporan/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/donasi' | '/kegiatan' | '/tentang' | '/laporan/$slug' | '/laporan'
  id:
    | '__root__'
    | '/'
    | '/donasi'
    | '/kegiatan'
    | '/tentang'
    | '/laporan/$slug'
    | '/laporan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DonasiRoute: typeof DonasiRoute
  KegiatanRoute: typeof KegiatanRoute
  TentangRoute: typeof TentangRoute
  LaporanSlugRoute: typeof LaporanSlugRoute
  LaporanIndexRoute: typeof LaporanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kegiatan': {
      id: '/kegiatan'
      path: '/kegiatan'
      fullPath: '/kegiatan'
      preLoaderRoute: typeof KegiatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donasi': {
      id: '/donasi'
      path: '/donasi'
      fullPath: '/donasi'
      preLoaderRoute: typeof DonasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/': {
      id: '/laporan/'
      path: '/laporan'
      fullPath: '/laporan/'
      preLoaderRoute: typeof LaporanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/$slug': {
      id: '/laporan/$slug'
      path: '/laporan/$slug'
      fullPath: '/laporan/$slug'
      preLoaderRoute: typeof LaporanSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DonasiRoute: DonasiRoute,
  KegiatanRoute: KegiatanRoute,
  TentangRoute: TentangRoute,
  LaporanSlugRoute: LaporanSlugRoute,
  LaporanIndexRoute: LaporanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
